### ISSUE TITLE
the rf frontend

### ISSUE THREAD

**Issue by iceberg1369** [globsky/greta-oto#2]
what is the rf frontend IC you use or recommend?

**Comment by globsky** [comment]
The baseband design is adaptable to a wide range of RF front-end (some need
to do sampling rate adjustment and/or a simple filter) like MAX2769/2771.
But for power efficiency, it is better to have a customized RF.

**Comment by iceberg1369** [comment]
The 2771 is 2bit adc but the code requires 4bit samples. Is 4bit adc even needed. As far as I know 4bit samples has zero impact on snr

**Comment by globsky** [comment]
2bit is at the over sampling situation (eg. 16MHz) and you will get more sampling bits when you do down sampling. And theoretically, 4bits has more than 1dB SNR gain than 2bits and 12dB better for anti-interference. How ever MAX2771 is just one choice. It is better to have customized RF because commercial GNSS receiver all have RF integrated with baseband.
