### ISSUE TITLE
部分代码错误

### ISSUE THREAD

**Issue by zhangyp1618** [globsky/greta-oto#6]
ae_prn_gen.v：369行, default: {insert_index_l1c, weil_index_l1c} = 28'h0;
amp_compare.v：index为output；
multiply_4x4.v: value_o为output；
另外，请问怎么才能把fpga+mcu跑起来，在哪个平台呢。感谢分享。

**Comment by globsky** [comment]
Thanks for reminding. Will be corrected in next release.
The hardware platform is not ready yet due to following reason:
RF front-end, SoC platform and RTOS not yet decided.
I know that ZYNQ+MAX2769/2771+FreeRTOS/RTThread will work. But at current stage I will first focus on coding especially firmware.

**Comment by globsky** [comment]
Fixed
